Added an api call to camd-services to send evaluation failure emails
US-EPA-CAMD/easey-quartz-scheduler pull request #189
Opened 2024-11-04 16:48 UTC by yonatan-dp

…ation emails when evaluations fail.

## Pull Request

Added an api call to camd-services to send evaluation failure notification emails when evaluations fail.

2024-11-04 22:27 UTC, maxdiebold-erg requested changes
Looks good, I left just one small suggestion below.

2024-11-04 22:27 UTC, maxdiebold-erg commented on admin/Models/EvaluationStageDto.cs
> +}
The pattern for other models is to wrap the class in the `Epa.Camd.Quartz.Scheduler.Models` namespace:
```suggestion
namespace Epa.Camd.Quartz.Scheduler.Models
{
    public class EvaluationStageDto
    {
        public string action { get; set; }
        public string dateTime { get; set; }
    }
}
```

2024-11-05 17:19 UTC, yonatan-dp commented on admin/Models/EvaluationStageDto.cs
> +}
Updated per comment.

2024-11-05 17:54 UTC, maxdiebold-erg approved these changes

2024-11-05 20:19 UTC, merged